kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: "https://github.com/vrutkovs/muchanizer"
    argocd.argoproj.io/sync-wave: "3"
  name: mirror-bot
  namespace: muchanizer
  labels:
    app: muchanizer
    app.kubernetes.io/component: muchanizer
    app.kubernetes.io/instance: muchanizer
    app.kubernetes.io/name: muchanizer
    app.kubernetes.io/part-of: muchanizer-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.12-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "muchanizer:bot"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/vrutkovs/muchanizer"
    contextDir: /src/bot
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: muchanizer-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: muchanizer-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
