kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hg-cache
  namespace: muchanizer
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
